a=[1,2,3,4]
console.log(a);
a.push(5)
console.log(a);
a.pop();
console.log(a);
a.unshift(5);
console.log(a);
a.shift()
console.log(a);
a2=[5,4,3,5,9]
console.log(a2.sort((a,b)=>a-b));
console.log(a2.sort((a,b)=>b-a));
a=[[1,2],[3,4,6,[7,8]]]
console.log(a.flat());
a=[[1,1],[2,4],[3,3]]
console.log(a.map(item=>item[1]));
a=[1,2,3,4]
console.log(a.reduce((d1,d2)=>d1+d2));
console.log(a.reduce((d1,d2)=>d1>d2?d1:d2));
console.log(a.reduce((d1,d2)=>d1<d2?d1:d2));
console.log(a.filter(item=>item>2));
console.log(a.some(item=>item>2));
console.log(a.find(item=>item>2));
console.log(a.includes(2));
console.log(a.reduce((d1,d2)=>d1+d2)/a.length);
a.splice(3,1,5,6)
console.log(a);
console.log(a.slice(1,4));
console.log(a.indexOf(2));
console.log(`slice`);
a2=a.slice(1,3);
console.log(a2);
str='Hello am Sanjay'
console.log(str.toUpperCase());
console.log(str.toLowerCase());
str1=str.replace('Sanjay','Subin');
console.log(str1);
str2=str.substring(0,3)
console.log(str2);
vowels=['a','e','i','o','u']
op=[];
Array.from(str).filter(letter=>vowels.includes(letter)&&!op.includes(letter)&&op.push(letter))
console.log(op);